"""add phone number

Revision ID: da4dc7c35008
Revises: df08a845d1b9
Create Date: 2022-07-17 17:37:05.224451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4dc7c35008'
down_revision = 'df08a845d1b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    return None
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
